# Generated by Django 5.1.3 on 2024-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='social_id',
            field=models.CharField(max_length=50),
        ),
    ]
