# Generated by Django 5.1.3 on 2024-11-08 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(db_column='cloth_id', primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('image', models.URLField(max_length=255)),
                ('type', models.IntegerField()),
                ('label_num', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
